default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  encoding: unicode
  database: tomatocan
  username: vinhnguyen1999

test:
  <<: *default
  encoding: unicode
  database: TestTomatoCan
  username: vinhnguyen1999

production:
  <<: *default
